In [1]:
# Importação das bibliotecas necessárias
import streamlit as st         # Biblioteca para criação de dashboards
import pandas as pd           # Biblioteca para manipulação de dados
import matplotlib.pyplot as plt  # Para gráficos

In [2]:
# Carregando o arquivo de dados
df = pd.read_csv("finanAgroGoias2014-2024.csv" , encoding='utf-8', sep=';', decimal=',')
df.head()

,Localidade,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Abadia de Goiás,"1.682.176,83","359.230,36","843.952,23","524.909,59",1.102.677,944.144,2.116.228,4.646.637,3.565.464,2.370.000,2.819.375
1,Abadiânia,"14.843.437,29","15.326.296,30","19.138.436,47","24.447.300,06",17.306.762,20.822.652,21.229.967,35.531.783,40.681.067,37.894.251,43.155.083
2,Acreúna,"73.946.829,36","66.921.824,54","65.892.466,02","57.529.854,14",79.768.468,89.626.284,89.487.837,160.586.438,175.883.187,138.525.655,144.786.963
3,Adelândia,"47.155,75","53.000,00","96.800,00",-,1.013.365,647.285,1.340.922,2.699.809,7.966.268,840.000,5.645.106
4,Água Fria de Goiás,"97.449.438,98","97.130.008,25","79.667.062,28","81.113.135,54",97.395.702,122.200.333,167.341.415,177.472.154,111.771.836,105.053.474,255.453.433

In [3]:
#troca todos os '-' por zero
df = df.replace('-', 0)
df = df.replace('.', '')
df.head(10)

,Localidade,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Abadia de Goiás,"1.682.176,83","359.230,36","843.952,23","524.909,59",1.102.677,944.144,2.116.228,4.646.637,3.565.464,2.370.000,2.819.375
1,Abadiânia,"14.843.437,29","15.326.296,30","19.138.436,47","24.447.300,06",17.306.762,20.822.652,21.229.967,35.531.783,40.681.067,37.894.251,43.155.083
2,Acreúna,"73.946.829,36","66.921.824,54","65.892.466,02","57.529.854,14",79.768.468,89.626.284,89.487.837,160.586.438,175.883.187,138.525.655,144.786.963
3,Adelândia,"47.155,75","53.000,00","96.800,00",0,1.013.365,647.285,1.340.922,2.699.809,7.966.268,840.000,5.645.106
4,Água Fria de Goiás,"97.449.438,98","97.130.008,25","79.667.062,28","81.113.135,54",97.395.702,122.200.333,167.341.415,177.472.154,111.771.836,105.053.474,255.453.433
5,Água Limpa,"324.152,40","13.140,00","338.389,57","243.862,66",74.139,0,0,0,1.115.390,0,1.260.877
6,Águas Lindas de Goiás,"4.208,80","149.965,60","6.034,66","153.857,71",58.417,47.728,0,806.304,1.476.308,280.000,1.554.449
7,Alexânia,"15.114.336,49","19.384.383,89","18.286.696,64","15.341.546,22",17.200.434,20.543.029,20.218.600,29.474.601,38.205.046,85.600.646,82.860.155
8,Aloândia,"4.232.029,45","3.366.721,39","3.761.660,97","6.370.755,49",5.703.124,5.588.598,9.057.391,17.651.700,13.035.200,9.011.990,20.891.653
9,Alto Horizonte,"1.355.749,35","869.241,08","1.286.219,65","1.029.134,44",1.040.729,1.058.977,814.752,3.352.754,5.648.757,660.450,2.776.522

In [4]:
#verificar o tipo de dado das colunas
df.dtypes

Localidade    object
2014          object
2015          object
2016          object
2017          object
2018          object
2019          object
2020          object
2021          object
2022          object
2023          object
2024          object
dtype: object

In [5]:
#verificando o tipo de dado das colunas
tipos = df['2014'].apply(type)
print(tipos)

0      <class 'str'>
1      <class 'str'>
2      <class 'str'>
3      <class 'str'>
4      <class 'str'>
           ...
241    <class 'str'>
242    <class 'str'>
243    <class 'str'>
244    <class 'str'>
245    <class 'str'>
Name: 2014, Length: 246, dtype: object

In [6]:
# df.iloc[:, 1:] seleciona todas as colunas, exceto a primeira
# col.str.replace('.', '', regex=False) remove os pontos e 
# col.str.replace(',', '.', regex=False) troca a vírgula por ponto
df.iloc[:, 1:] = df.iloc[:, 1:].apply(
    lambda col: pd.to_numeric(
        col.str.replace('.', '', regex=False).str.replace(',', '.', regex=False),
        errors='coerce'
    )
)

In [7]:
df.head(10)

,Localidade,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Abadia de Goiás,1682176.83,359230.36,843952.23,524909.59,1102677,944144,2116228.0,4646637.0,3565464.0,2370000.0,2819375.0
1,Abadiânia,14843437.29,15326296.3,19138436.47,24447300.06,17306762,20822652,21229967.0,35531783.0,40681067.0,37894251.0,43155083.0
2,Acreúna,73946829.36,66921824.54,65892466.02,57529854.14,79768468,89626284,89487837.0,160586438.0,175883187.0,138525655.0,144786963.0
3,Adelândia,47155.75,53000.0,96800.0,NaN,1013365,647285,1340922.0,2699809.0,7966268.0,840000.0,5645106.0
4,Água Fria de Goiás,97449438.98,97130008.25,79667062.28,81113135.54,97395702,122200333,167341415.0,177472154.0,111771836.0,105053474.0,255453433.0
5,Água Limpa,324152.4,13140.0,338389.57,243862.66,74139,0,NaN,NaN,1115390.0,0.0,1260877.0
6,Águas Lindas de Goiás,4208.8,149965.6,6034.66,153857.71,58417,47728,NaN,806304.0,1476308.0,280000.0,1554449.0
7,Alexânia,15114336.49,19384383.89,18286696.64,15341546.22,17200434,20543029,20218600.0,29474601.0,38205046.0,85600646.0,82860155.0
8,Aloândia,4232029.45,3366721.39,3761660.97,6370755.49,5703124,5588598,9057391.0,17651700.0,13035200.0,9011990.0,20891653.0
9,Alto Horizonte,1355749.35,869241.08,1286219.65,1029134.44,1040729,1058977,814752.0,3352754.0,5648757.0,660450.0,2776522.0

In [8]:
#Verificando o tipo de dado da coluna 2020
tipos = df['2020'].apply(type)
tipos.head(10)

0    <class 'float'>
1    <class 'float'>
2    <class 'float'>
3    <class 'float'>
4    <class 'float'>
5    <class 'float'>
6    <class 'float'>
7    <class 'float'>
8    <class 'float'>
9    <class 'float'>
Name: 2020, dtype: object

In [9]:
# Calcula a média das colunas a partir da segunda (colunas de 2014 a 2024) para cada linha (localidade)
#arrendondar para duas casas decimais
df["Md_Invest"] = df.iloc[:, 1:].mean(axis=1)

#arrendondar para duas casas decimais
df["Md_Invest"] = df["Md_Invest"].round(2)

df

,Localidade,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,Md_Invest
0,Abadia de Goiás,1682176.83,359230.36,843952.23,524909.59,1102677,944144,2116228.0,4646637.0,3565464.0,2370000.0,2819375.0,1906799.455455
1,Abadiânia,14843437.29,15326296.3,19138436.47,24447300.06,17306762,20822652,21229967.0,35531783.0,40681067.0,37894251.0,43155083.0,26397912.283636
2,Acreúna,73946829.36,66921824.54,65892466.02,57529854.14,79768468,89626284,89487837.0,160586438.0,175883187.0,138525655.0,144786963.0,103905073.278182
3,Adelândia,47155.75,53000.0,96800.0,NaN,1013365,647285,1340922.0,2699809.0,7966268.0,840000.0,5645106.0,2034971.075
4,Água Fria de Goiás,97449438.98,97130008.25,79667062.28,81113135.54,97395702,122200333,167341415.0,177472154.0,111771836.0,105053474.0,255453433.0,126549817.459091
...,...,...,...,...,...,...,...,...,...,...,...,...,...
241,Varjão,836572.03,623855.24,863944.19,882105.0,2098703,2565257,4001215.0,10573142.0,18536744.0,3157898.0,12787988.0,5175220.314545
242,Vianópolis,51356193.09,53595151.35,57405591.8,58848206.0,77113410,90882556,125963473.0,162980705.0,164261974.0,77476446.0,147101177.0,96998625.749091
243,Vicentinópolis,133944098.56,73383500.41,46959809.47,44329400.0,63392742,73448152,70383308.0,86431911.0,78195547.0,22358242.0,137729842.0,75505141.130909
244,Vila Boa,2409721.07,794700.0,4041859.87,2832749.0,8194807,9790047,25493221.0,24018673.0,6670162.0,4393870.0,5209409.0,8531747.176364
245,Vila Propício,23932044.48,18523705.12,21073277.35,36383702.0,35579803,39313211,42864425.0,80910414.0,79862125.0,43827791.0,103088532.0,47759911.813636

In [ ]:
# Inserir uma linha com a média de investimento para cada ano

# 1. Calcula a média das colunas de investimento (excluindo a coluna 'Localidade')
# df.iloc[:, 1:] seleciona todas as colunas a partir da segunda (índices dos anos)
mean_values = df.iloc[:, 1:].mean()

# 2. Cria uma lista com o rótulo "Média" para a primeira coluna e os valores médios para as demais
nova_linha = ["Média"] + mean_values.tolist()

# 3. Converte a lista em um DataFrame com as mesmas colunas do df original
linha_media = pd.DataFrame([nova_linha], columns=df.columns)

# 4. Concatena a nova linha ao dataframe original (ignore_index=True para reindexar)
df = pd.concat([df, linha_media], ignore_index=True)

df

,Localidade,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,Md_Invest
0,Abadia de Goiás,1682176.83,359230.36,843952.23,524909.59,1102677,944144,2116228.0,4646637.0,3565464.0,2370000.0,2819375.0,1906799.455455
1,Abadiânia,14843437.29,15326296.3,19138436.47,24447300.06,17306762,20822652,21229967.0,35531783.0,40681067.0,37894251.0,43155083.0,26397912.283636
2,Acreúna,73946829.36,66921824.54,65892466.02,57529854.14,79768468,89626284,89487837.0,160586438.0,175883187.0,138525655.0,144786963.0,103905073.278182
3,Adelândia,47155.75,53000.0,96800.0,NaN,1013365,647285,1340922.0,2699809.0,7966268.0,840000.0,5645106.0,2034971.075
4,Água Fria de Goiás,97449438.98,97130008.25,79667062.28,81113135.54,97395702,122200333,167341415.0,177472154.0,111771836.0,105053474.0,255453433.0,126549817.459091
...,...,...,...,...,...,...,...,...,...,...,...,...,...
242,Vianópolis,51356193.09,53595151.35,57405591.8,58848206.0,77113410,90882556,125963473.0,162980705.0,164261974.0,77476446.0,147101177.0,96998625.749091
243,Vicentinópolis,133944098.56,73383500.41,46959809.47,44329400.0,63392742,73448152,70383308.0,86431911.0,78195547.0,22358242.0,137729842.0,75505141.130909
244,Vila Boa,2409721.07,794700.0,4041859.87,2832749.0,8194807,9790047,25493221.0,24018673.0,6670162.0,4393870.0,5209409.0,8531747.176364
245,Vila Propício,23932044.48,18523705.12,21073277.35,36383702.0,35579803,39313211,42864425.0,80910414.0,79862125.0,43827791.0,103088532.0,47759911.813636
246,Média,35531847.759617,33217823.94681,35264390.564286,38795282.926726,41589124.768293,41185921.455285,49631037.419214,78124647.820513,73567255.65625,42839697.390947,86378814.302905,48377401.110548

In [11]:
# Seleciona as colunas numéricas (int e float)
numeric_cols = df.select_dtypes(include=['float', 'int']).columns

# Aplica o arredondamento de 2 casas decimais nas colunas numéricas
df[numeric_cols] = df[numeric_cols].round(2)

df

,Localidade,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,Md_Invest
0,Abadia de Goiás,1682176.83,359230.36,843952.23,524909.59,1102677,944144,2116228.0,4646637.0,3565464.0,2370000.0,2819375.0,1906799.455455
1,Abadiânia,14843437.29,15326296.3,19138436.47,24447300.06,17306762,20822652,21229967.0,35531783.0,40681067.0,37894251.0,43155083.0,26397912.283636
2,Acreúna,73946829.36,66921824.54,65892466.02,57529854.14,79768468,89626284,89487837.0,160586438.0,175883187.0,138525655.0,144786963.0,103905073.278182
3,Adelândia,47155.75,53000.0,96800.0,NaN,1013365,647285,1340922.0,2699809.0,7966268.0,840000.0,5645106.0,2034971.075
4,Água Fria de Goiás,97449438.98,97130008.25,79667062.28,81113135.54,97395702,122200333,167341415.0,177472154.0,111771836.0,105053474.0,255453433.0,126549817.459091
...,...,...,...,...,...,...,...,...,...,...,...,...,...
242,Vianópolis,51356193.09,53595151.35,57405591.8,58848206.0,77113410,90882556,125963473.0,162980705.0,164261974.0,77476446.0,147101177.0,96998625.749091
243,Vicentinópolis,133944098.56,73383500.41,46959809.47,44329400.0,63392742,73448152,70383308.0,86431911.0,78195547.0,22358242.0,137729842.0,75505141.130909
244,Vila Boa,2409721.07,794700.0,4041859.87,2832749.0,8194807,9790047,25493221.0,24018673.0,6670162.0,4393870.0,5209409.0,8531747.176364
245,Vila Propício,23932044.48,18523705.12,21073277.35,36383702.0,35579803,39313211,42864425.0,80910414.0,79862125.0,43827791.0,103088532.0,47759911.813636
246,Média,35531847.759617,33217823.94681,35264390.564286,38795282.926726,41589124.768293,41185921.455285,49631037.419214,78124647.820513,73567255.65625,42839697.390947,86378814.302905,48377401.110548